const mongoose = require('mongoose');

// Define the schema for AttendanceLog
const attendanceLogSchema = new mongoose.Schema({
  EmployeeName: { type: String, required: true },
  EmployeeCode: { type: String, required: true },
  Gender: { type: String, required: true },
  Designation: { type: String, default: "" },
  CategoryId: { type: Number, required: true },
  EmployementType: { type: String, default: "Permanent" },
  EmployeeDevicePassword: { type: String, default: "" },
  FatherName: { type: String, default: "" },
  MotherName: { type: String, default: "" },
  ResidentialAddress: { type: String, default: "" },
  PermanentAddress: { type: String, default: "" },
  ContactNo: { type: String, default: "" },
  Email: { type: String, default: "" },
  DOB: { type: Date, default: "1900-01-01T00:00:00.000Z" },
  Location: { type: String, default: "" },
  WorkPlace: { type: String, default: null },
  ExtensionNo: { type: String, default: null },
  LoginName: { type: String, default: null },
  LoginPassword: { type: String, default: null },
  EmployeePhoto: { type: String, default: null },
  AttendanceLogId: { type: Number, required: true },
  AttendanceDate: { type: Date, required: true },
  EmployeeId: { type: Number, required: true },
  InTime: { type: String, default: "1900-01-01 00:00:00" },
  InDeviceId: { type: String, default: "" },
  OutTime: { type: String, default: "1900-01-01 00:00:00" },
  OutDeviceId: { type: String, default: "" },
  Duration: { type: Number, default: 0 },
  LateBy: { type: Number, default: 0 },
  EarlyBy: { type: Number, default: 0 },
  IsOnLeave: { type: Number, default: 0 },
  LeaveType: { type: String, default: "" },
  LeaveDuration: { type: Number, default: 0 },
  WeeklyOff: { type: Number, default: 0 },
  Holiday: { type: Number, default: 0 },
  LeaveRemarks: { type: String, default: "" },
  PunchRecords: { type: String, default: "" },
  ShiftId: { type: Number, required: true },
  Present: { type: Number, default: 0 },
  Absent: { type: Number, default: 1 },
  Status: { type: String, default: "Absent" },
  StatusCode: { type: String, default: "A" },
  P1Status: { type: String, default: "" },
  P2Status: { type: String, default: "" },
  P3Status: { type: String, default: "" },
  IsonSpecialOff: { type: Number, default: 0 },
  SpecialOffType: { type: String, default: "" },
  SpecialOffRemark: { type: String, default: "" },
  SpecialOffDuration: { type: Number, default: 0 },
  OverTime: { type: Number, default: 0 },
  OverTimeE: { type: Number, default: -1 },
  MissedOutPunch: { type: Number, default: 0 },
  Remarks: { type: String, default: "" },
  MissedInPunch: { type: String, default: null },
  C1: { type: String, default: null },
  C2: { type: String, default: null },
  C3: { type: String, default: null },
  C4: { type: String, default: null },
  C5: { type: String, default: null },
  C6: { type: String, default: null },
  C7: { type: String, default: null },
  LeaveTypeId: { type: Number, default: 0 },
  LossOfHours: { type: Number, default: 0 }
}, { timestamps: true }); // Timestamps for createdAt and updatedAt

// Create a model based on the schema
const AttendanceLogModel = mongoose.model('AttendanceLog', attendanceLogSchema);

module.exports = AttendanceLogModel;
