const mongoose = require("mongoose");

const AttendanceLogSchema = new mongoose.Schema({
  EmployeeName: String,
  EmployeeCode: String,
  Gender: String,
  Designation: String,
  CategoryId: Number,
  EmployementType: String,
  EmployeeDevicePassword: String,
  FatherName: String,
  MotherName: String,
  ResidentialAddress: String,
  PermanentAddress: String,
  ContactNo: String,
  Email: String,
  DOB: Date,
  Location: String,
  WorkPlace: String,
  ExtensionNo: String,
  LoginName: String,
  LoginPassword: String,
  EmployeePhoto: String,
  AttendanceLogId: { type: Number, unique: true }, // Unique identifier
  AttendanceDate: Date,
  EmployeeId: Number,
  InTime: String,
  InDeviceId: String,
  OutTime: String,
  OutDeviceId: String,
  Duration: Number,
  LateBy: Number,
  EarlyBy: Number,
  IsOnLeave: Number,
  LeaveType: String,
  LeaveDuration: Number,
  WeeklyOff: Number,
  Holiday: Number,
  LeaveRemarks: String,
  PunchRecords: String,
  ShiftId: Number,
  Present: Number,
  Absent: Number,
  Status: String,
  StatusCode: String,
  P1Status: String,
  P2Status: String,
  P3Status: String,
  IsonSpecialOff: Number,
  SpecialOffType: String,
  SpecialOffRemark: String,
  SpecialOffDuration: Number,
  OverTime: Number,
  OverTimeE: Number,
  MissedOutPunch: Number,
  Remarks: String,
  MissedInPunch: String,
  C1: String,
  C2: String,
  C3: String,
  C4: String,
  C5: String,
  C6: String,
  C7: String,
  LeaveTypeId: Number,
  LossOfHours: Number,
});

const AttendanceLogModel = mongoose.model("AttendanceLog", AttendanceLogSchema);

module.exports = AttendanceLogModel;
